artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_path: Experiments\Kaggle_Training_Dataset_v2.csv
  #local_data_file: artifacts/data_ingestion/data.zip
  local_file_dir: artifacts/data_ingestion/data.csv

data_validation:
  root_dir: artifacts/data_validation
  target: artifacts/data_ingestion/data.csv
  result: artifacts/data_validation/result.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/data.csv

model_training:
  root_dir: artificats/model_training
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  
  
  
  

